nuagenetworks/nuage-metroae

Documentation/RELEASE_NOTES.md
pip_requirements.txt
src/playbooks/build.yml

Upgrade minimum ansible version to 2.9.2

Upgrade minimum ansible version to 2.9.2

---

Documentation/RELEASE_NOTES.md
deployments/default/common.yml
examples/active_standby_vsds/common.yml
examples/blank_deployment/common.yml
examples/kvm_datacenter_install/common.yml
examples/kvm_portal_install/common.yml
examples/kvm_sdwan_install/common.yml
examples/kvm_vsc_upgrade/common.yml
examples/kvm_vsd_install/common.yml
schemas/common.json
src/deployment_templates/common.j2
src/roles/common/templates/group_vars.all.j2

Change default NUH ram to 8 GB from 4 GB (METROAE-1355)

Change default NUH Ram to 8 gb

---

src/roles/common/tasks/vsc-process-vars.yml
src/roles/common/templates/hosts.j2

Fix IPv6 VSC install errors

---

Documentation/RELEASE_NOTES.md
openstack_requirements.txt
src/roles/common/tasks/check-upgrade-prereq.yml

Fix VCENTER based VSD and VSC upgrades using container

Fix VCENTER upgrades using container

---

Documentation/RELEASE_NOTES.md
src/roles/common/templates/nuhs.j2
src/roles/nuh-deploy/tasks/main.yml

Fix CPU pinning for NUH and perform NTP sync (METROAE-1397)

Fix CPU pinning for NUH and perform NTP sync

---

Documentation/RELEASE_NOTES.md
deployments/default/common.yml
examples/active_standby_vsds/common.yml
examples/aws_sdwan_install/common.yml
examples/aws_sdwan_upgrade/common.yml
examples/blank_deployment/common.yml
examples/kvm_datacenter_install/common.yml
examples/kvm_portal_install/common.yml
examples/kvm_sdwan_install/common.yml
examples/kvm_vsc_upgrade/common.yml
examples/kvm_vsd_install/common.yml
examples/openstack_install/common.yml
examples/upgrade_datacenter_vcenter/common.yml
examples/vcenter_datacenter_install/common.yml
schemas/common.json
src/deployment_templates/common.j2
src/roles/common/templates/group_vars.all.j2
src/roles/vsd-deploy/tasks/main.yml
src/roles/vsd-deploy/tasks/renew_ejabberd_license.yml

Add support to add Ejabberd license file install via Metro

Add support to add Ejabberd license file install via Metro

---

openstack_requirements.txt

Fix container build issues for setuptools

Fix container build issues

---

src/roles/common/templates/group_vars.all.j2

A scheduled test to run when use_vsc_fallocate_size_gb is evaluated to false, or true, accordingly the vsc_fallocate_size_gb is equated to 1 or 0

Vscfallocate

---

Documentation/RELEASE_NOTES.md
deployments/default/vscs.yml
examples/aws_sdwan_install/vscs.yml
examples/aws_sdwan_upgrade/vscs.yml
examples/blank_deployment/vscs.yml
examples/kvm_datacenter_install/vscs.yml
examples/kvm_sdwan_install/vscs.yml
examples/kvm_vsc_upgrade/vscs.yml
examples/nsgv_bootstrap/vscs.yml
examples/openstack_install/vscs.yml
examples/upgrade_datacenter_vcenter/vscs.yml
examples/vcenter_datacenter_install/vscs.yml
schemas/vscs.json
src/deployment_templates/vscs.j2
src/playbooks/with_build/vsc_apply_config.yml
src/roles/common/tasks/vsc-apply-config.yml
src/roles/common/templates/vsc.j2
src/roles/vsc-deploy/tasks/main.yml

Apply VSC Custom Configurations

---

openstack_requirements.txt

Update setuptools for master

---

src/roles/nuh-deploy/tasks/main.yml
src/roles/vstat-deploy/tasks/main.yml

Disable cloud init and chrony on VSTAT and NUH if present

Disable cloud init and chrony on VSTAT and NUH if present

---

src/roles/common/tasks/disable-stats-on-vsd.yml
src/roles/common/tasks/get-vsd-build.yml
src/roles/common/tasks/get-vsd-version.yml
src/roles/common/tasks/vsd-node-info.yml
src/roles/common/tasks/vstat-enable-stats.yml
src/roles/vsd-cluster-failover/tasks/main.yml
src/roles/vsd-upgrade-complete/tasks/main.yml

moved the get vsd version and get vsd build to common/tasks

Vsdversion

---

Documentation/RELEASE_NOTES.md

Disable chrony and cloud-init for NUH and VSTATs install (METROAE-1401)

Disable chrony and cloud-init for NUH and VSTATs install (METROAE-1401)

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-dbbackup/tasks/main.yml

Disable maintainance mode for inplace upgrades

Disable maintainance mode for inplace upgrades

---

Documentation/SETUP.md
pip_requirements.txt
yum_requirements.txt

JIRA ticket: http://mvjira.mv.usa.alcatel.com:8080/browse/METROAE-1408

Python Virtual Environment Documentation

---

Documentation/RELEASE_NOTES.md
examples/blank_deployment/nuh_external_interfaces.yml
examples/kvm_sdwan_install/nuh_external_interfaces.yml
examples/kvm_sdwan_install/nuhs.yml
examples/minimum_required_blank_deployment/nuh_external_interfaces.yml
examples/nsgv_bootstrap/nuh_external_interfaces.yml
schemas/nuh_external_interfaces.json
src/deployment_templates/nuh_external_interfaces.j2
src/raw_example_data/kvm_sdwan_install/nuh_external_interfaces.yml
src/raw_example_data/kvm_sdwan_install/nuhs.yml
src/raw_example_data/nsgv_bootstrap/nuh_external_interfaces.yml
src/roles/common/tasks/nuh-process-vars.yml
src/roles/common/templates/nuhs.j2
src/roles/nuh-deploy/tasks/main.yml
src/roles/nuh-deploy/templates/config.yml.j2

Add support for NUH multiple external interfaces

Add support for NUH multiple external interfaces

---

Documentation/RELEASE_NOTES.md
src/roles/common/tasks/vsd-generate-transfer-certificates.yml

Check connectivity before certificate generation and transfer from VSD

Check connectivity before certificate generation and transfer from VSD 

---

src/roles/common/tasks/vsd-generate-transfer-certificates.yml

Add Ipv6 check for connectivity before cert transfer

Add Ipv6 check for connectivity before cert transfer

---

src/roles/common/tasks/vsd-generate-transfer-certificates.yml

Fix vsd transfer certificate error

Fix vsd transfer certificate error

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-cluster-failover/tasks/main.yml

Add Missing quotes for active standby

Add Missing quotes for active standby 

---

src/roles/vsd-cluster-failover/tasks/main.yml

Add missing quote for VSD active standby

Add missing quote for VSD active standby

---

Documentation/RELEASE_NOTES.md
src/playbooks/with_build/copy_qcow2_files.yml
src/roles/common/tasks/check-predeploy-prereq.yml
src/roles/nsgv-predeploy/tasks/kvm.yml
src/roles/vnsutil-predeploy/tasks/kvm.yml
src/roles/vsc-predeploy/tasks/kvm.yml
src/roles/vsd-cluster-failover/tasks/main.yml
src/roles/vsd-predeploy/tasks/kvm.yml
src/roles/vsr-predeploy/tasks/kvm_deploy_image_file.yml
src/roles/vstat-predeploy/tasks/kvm.yml

Reverts nuagenetworks/nuage-metroae#1588. It went into master by mistake.

Revert "Qcow2 copy fix"

---

src/roles/vsd-cluster-failover/tasks/main.yml

Fix active standby Failover issue

Fix active standby Failover issue

---

get_debug.py

Added the following requirements:
1) Prints the names of the files it is included in the archive.
2) Prints the path and name of the tar.gz file that was created
3) If it can't find a file, printing the equivalent missing file and its skipping.

Get debug update

---

run_wizard.py

updating version number regular expression to work for 20.10.X train

---

src/roles/common/tasks/vsd-node-info.yml
src/roles/common/tasks/vsd-transfer-truststore.yml

Also includes some fixes (undoing linting changes) that cause stats-out to fail.

Fixes for showStatus with custom VSD user

---

src/roles/common/tasks/set-major-minor-versions.yml

Make 6.0.3 to 20.10.X and beyond and major upgrade

Make 6.0.3 to 20.10.X and beyond and major upgrade

---

Documentation/RELEASE_NOTES.md
metroae

Fixes the metroae script to not fail when updating itself.  Has a corresponding test branch change.

Metroae update fix

---

Documentation/RELEASE_NOTES.md
yum_requirements.txt

Add rsync package to yum requirements

Add rsync package to yum requirements

---

openstack_requirements.txt
pip_requirements.txt

Reverts nuagenetworks/nuage-metroae#1653

Revert "updated_cryptography_version"

---

openstack_requirements.txt
pip_requirements.txt

- Changes
- Changed cryptography version to 3.2 to overcome potential security vulnerabilities.

Cryptography version change

---

src/roles/vsc-upgrade-deploy/vars/main.yml

Fix json validation error

---

Documentation/RELEASE_NOTES.md
src/playbooks/with_build/vstat_health.yml

Remove VSTAT VSD health from VSTAT health

Remove VSTAT VSD health from VSTAT health

---

src/roles/nuh-postdeploy/tasks/main.yml

NUH postdeploy changes for internal interfaces

NUH postdeploy changes for internal interfaces

---

pip_requirements.txt

Fix setup error for Metro setupscript

Fix setup error for Metro setupscript

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-deploy/tasks/main.yml

Fix vsd-install script parameters (METROAE-347)

Fix vsd-install script parameters

---

src/roles/nuh-deploy/tasks/main.yml

NUH Notifications fix

---

openstack_requirements.txt

Openstack requirements package fix

Openstack requirements package fix

---

src/playbooks/build.yml

checking inventory file present or not and checking vsd_auth variable present in the file

Improve playbook

---

Documentation/RELEASE_NOTES.md
src/roles/common/templates/webfilter.j2
src/roles/webfilter-predeploy/tasks/kvm.yml

Fix webfilter install required bridges issue (METROAE-371)

Fix Webfilter Predeploy issue

---

examples/plugins/full/roles/demovm-predeploy/tasks/main.yml

To support container-plugin-test

demovm modified for test

---

pip_requirements.txt

Revert ansible back to 2.9.2

---

Documentation/RELEASE_NOTES.md
src/roles/vnsutil-deploy/tasks/openstack.yml
src/roles/vnsutil-destroy/tasks/openstack.yml
src/roles/vnsutil-predeploy/tasks/openstack.yml
src/roles/vsc-destroy/tasks/openstack.yml
src/roles/vsc-predeploy/tasks/openstack.yml
src/roles/vsd-destroy/tasks/openstack.yml
src/roles/vsd-predeploy/tasks/openstack.yml
src/roles/vstat-deploy/tasks/openstack.yml
src/roles/vstat-destroy/tasks/openstack.yml
src/roles/vstat-predeploy/tasks/openstack.yml

Fix openstack ssl connection error (METROAE-425)

Fix openstack ssl connection error

---

metroae

Container persmission fix

---

src/playbooks/with_build/upgrade_vsds_inplace.yml
src/roles/common/templates/hosts.j2

Fix Inplace SA upgrade

---

src/roles/vsd-deploy/tasks/main.yml
src/roles/vstat-deploy/tasks/main.yml

Fix VSD stats-out 20.10.R1 install

Fix VSD stats-out 20.10.R1 install

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-upgrade-prepare-for-deploy/tasks/main.yml

Check for matched and not examined files during upgrade prep

Check for matched and not examined files during upgrade prep

---

src/roles/nsgv-predeploy/tasks/vcenter.yml

remove extra debug line

---

src/roles/nsgv-predeploy/tasks/vcenter.yml

Reverts nuagenetworks/nuage-metroae#1756

Revert "remove extra debug line"

---

Documentation/RELEASE_NOTES.md
Documentation/UPGRADE_HA.md
src/menu
src/playbooks/with_build/upgrade_standby_vsds_inplace.yml
src/playbooks/with_build/upgrade_vsds.yml
src/roles/common/templates/hosts.j2
src/roles/nsgv-predeploy/tasks/vcenter.yml

Fix Standby upgrades for inplace patch

Fix Standby upgrades for inplace patch

---

Documentation/RELEASE_NOTES.md
openstack_requirements.txt
pip_requirements.txt

Here are the upgraded packages that are installed on vcenter node
> [caso@jen-vcenter-node ~]$ pip freeze
ansible==2.9.7
ansible-lint==4.1.0
appdirs==1.4.4
backports.ssl-match-hostname==3.5.0.1
bambou==3.1.1
bcrypt==3.1.7
certifi==2019.11.28
cffi==1.13.1
chardet==3.0.4
colander==0.9.9
colorama==0.4.3
configobj==4.7.2
configparser==4.0.2
contextlib2==0.6.0.post1
cryptography==3.3.2
decorator==3.4.0
distlib==0.3.1
distro==1.5.0
entrypoints==0.3
enum34==1.1.6
et-xmlfile==1.1.0
ethtool==0.8
filelock==3.0.12
flake8==3.0.4
Flask==0.10.1
functools32==3.2.3.post2
future==0.18.2
futures==3.1.1
idna==2.9
importlib-metadata==1.7.0
importlib-resources==3.0.0
iniparse==0.4
ipaddr==2.2.0
ipaddress==1.0.16
IPy==0.75
isc==2.0
iso8601==0.1.8
itsdangerous==1.1.0
javapackages==1.0.0
jdcal==1.4.1 …

Version 2.9.13

---

Documentation/RELEASE_NOTES.md
src/playbooks/with_build/vsd_stats_deploy.yml
src/roles/common/templates/group_vars.all.j2
src/roles/vsd-deploy/tasks/main.yml
src/roles/vsd-upgrade-inplace/tasks/main.yml
src/roles/vstat-deploy/tasks/main.yml

Add Support for Single-Step VSD Stats-out Upgrade and Patch (METROAE-470)

Add Support for Single-Step VSD Stats-out Upgrade and Patch

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-upgrade-inplace/tasks/main.yml

Apply VSD Branding for inplace upgrades (Metroae 469)

Apply VSD Branding for inplace upgrades

---

src/roles/nsgv-predeploy/templates/nsgv.xml.j2

adding nesç cpu changes for nsgv

---

src/roles/vsd-deploy/tasks/brand_vsd.yml

Wait for JBoss to be up on branding Restart. Fix as a part of dev branch changes. No release notes needed.

Wait for JBoss to be up on branding Restart

---

Documentation/RELEASE_NOTES.md
src/roles/nuh-destroy/tasks/kvm.yml
src/roles/nuh-destroy/tasks/main.yml
src/roles/nuh-destroy/tasks/vcenter.yml

[METROAE-506](https://jiradc2.ext.net.nokia.com/browse/METROAE-506)

Support destroying NUHs on VCenter

---

Documentation/RELEASE_NOTES.md
src/roles/vstat-destroy/tasks/vcenter.yml

Removed 3 redundant debug statements in vcenter.yml

Remove Debug Statements in vcenter.yml

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-decouple/tasks/main.yml

Allow VSD Decoupling to finish before check status

Allow VSD Decoupling to finish before check status

---

src/roles/vstat-deploy/tasks/main.yml

Vstat primary standby fixes

---

Documentation/RELEASE_NOTES.md
src/playbooks/with_build/brand_vsd.yml

Brand only primary VSDs

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-upgrade-complete/tasks/main.yml

Upgrade VSTATS if VSD GUI password has changed

Upgrade VSTATS correctly if VSD GUI password has changed

---

Documentation/RELEASE_NOTES.md
src/roles/common/templates/group_vars.all.j2
src/roles/common/templates/hosts.j2

Fix MetroAE errors while deploying using SSH Proxy (MetroAE-574)

Fix MetroAE errors while deploying using SSH Proxy

---

src/roles/vsd-deploy/tasks/vsd_security_hardening.yml
src/roles/vstat-health/tasks/main.yml
src/roles/vstat-postdeploy/tasks/main.yml

Fix proxy for non-root user. Part of changes for proxy fix. No additional release notes needed

Fix proxy for non-root user

---

.gitignore

Ignore mounted files for new container

Ignore mounted files for new container

---

metroae-container
src/validate_plugin.py

Make Plugins work with the new container

Make Plugins work with the new container

---

Documentation/RELEASE_NOTES.md
src/roles/common/tasks/set-major-minor-versions.yml

Fix upgrade from 20.10.R6.1 to 20.10.R6.3

Fix upgrade from 20.10.R6.1 to 20.10.R6.3

---

src/roles/vstat-update-license/tasks/main.yml

Add retries for VSTAT license patch

Add retries for VSTAT license patch

---

src/roles/vstat-update-license/tasks/main.yml

Fix VSTAT license expiry patch

Fix VSTAT license expiry patch

---

src/roles/vstat-update-license/tasks/main.yml

Fix errors in VSTAT license patching

Fix errors in VSTAT license patching 

---

generate_example_from_schema.py
run_wizard.py
src/callback_plugins/metroae_stdout.py
src/validate_schema_section.py

Requesting to merge after fixing documentation and string typos.
1. generate_example_from_schema.py line 273
Changed:
"Generates a example schema..."
To:
"Generates an example schema..."
2. run_wizard.py line 87
Changed:
"This optional step can beb used..."
To:
"This optional step can be used..."
3. src.validate_schema_section.py line 22
Changed "! There are two overlap " ...
To "! There are two overlapping " ...
4. src.validate_schema_section.py line 32
Changed: ' correspond to '
To: ' corresponding to '
5. src.callback_plugins.metroae_stdout.py line 47
Changed: # we care more about readable than accuracy...
To: # we care more about readability than accuracy...

Fixed typos.

---

src/playbooks/with_build/vsd_ha_upgrade_database_backup_and_decouple.yml

Fix double data backup for VSD HA upgrade

Fix double data backup for VSD HA upgrade

---

encrypt_credentials.py

Encrypt credentials fails with verbose params

Encrypt credentials fails with verbose params

---

src/roles/vstat-update-license/tasks/main.yml

Fix license issue for Vstat license patch

Fix license issue for Vstat license patch

---

Documentation/RELEASE_NOTES.md
src/roles/vsd-dbbackup/tasks/main.yml

Clean up temporary ISO file on VSD after mounting (METROAE-598)

Clean up temporary ISO file on VSD after mounting (METROAE-598)

---

ansible.cfg
src/roles/common/tasks/vsd-node-info.yml
src/roles/common/tasks/vstat-enable-stats.yml
src/roles/vsd-upgrade-complete/tasks/check_certificate_expiration_time.yml
src/roles/vstat-deploy/tasks/main.yml
src/roles/vstat-health/tasks/main.yml

Fix Hardening upgrades 

---

Documentation/RELEASE_NOTES.md
src/playbooks/with_build/brand_vsd.yml
src/roles/vsd-deploy/tasks/brand_vsd.yml
src/roles/vsd-deploy/tasks/main.yml

To resolve ticket: 
https://jiradc2.ext.net.nokia.com/browse/METROAE-597

MetroAE Branding Change

---

Documentation/CHANGES_IN_V5.md
Documentation/RELEASE_NOTES.md
README.md
src/roles/nsgv-predeploy/tasks/kvm.yml

Add documentation changes for v5

Add documentation changes for v5

---

Documentation/RELEASE_NOTES.md

Cleanup release notes for v5.1

Cleanup release notes for v5.1

---

src/roles/vsd-deploy/tasks/brand_vsd.yml

The link to passing job:
http://10.129.37.76:8080/job/nesc/job/UPGRADE-GCP-HA/124/

Fix branding

---

src/filter_plugins/vsc_filters.py
src/roles/vsc-health/tasks/main.yml

http://10.129.37.76:8080/job/alok/job/INSTALL_GCP_SA_COPY/96/
http://10.129.37.76:8080/job/alok/job/INSTALL_GCP_SA_COPY/97/

Vsc health check
